platform :ios, '11.0'
use_frameworks!

target 'ExampleDriverApp' do
  pod 'RideOsDriver', :path => '../../../RideOsDriver'
  pod 'RideOsApi', :path => '../../../../public/rideos-api-ios'
  pod 'RideOsGoogleMaps', :path => '../../../RideOsGoogleMaps'
  pod 'RideOsCommon', :path => '../../../RideOsCommon'
end
